name: Deploy to Elastic Beanstalk (prod)

on:
  push:
    branches: [ main, master ]

concurrency:
  group: eb-deploy-prod
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      APP_NAME: Reviews and Marketing
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: npm ci

      - name: Build and pack EB bundle
        run: bash scripts/pack_eb_bundle.sh

      - name: Deploy to EB
        env:
          ENV_NAME: ${{ secrets.EB_ENV_NAME }}
        run: bash scripts/deploy_eb.sh "$ENV_NAME"

